# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MAIN_BRANCH: github.ref == 'refs/heads/main'
jobs:

  test:
    runs-on: ubuntu-latest
    if: ${{env.MAIN_BRANCH}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Running tests
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    if: ${{env.MAIN_BRANCH}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{env.MAIN_BRANCH}}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gondalf" #Must be unique in Heroku
          heroku_email: "douglasleomendes@hotmail.com"
